# Generated by Django 3.0.5 on 2020-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemesgov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=500)),
                ('ministry', models.CharField(max_length=100)),
                ('dol', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('provisions', models.TextField()),
            ],
        ),
    ]
