# Generated by Django 3.0.5 on 2020-07-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemesgov',
            name='dol',
        ),
    ]
