# Generated by Django 3.0.5 on 2020-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_remove_schemesgov_dol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centralgov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_scheme', models.CharField(max_length=500)),
                ('c_ministry', models.CharField(max_length=100)),
                ('c_state', models.CharField(max_length=100)),
                ('c_status', models.CharField(max_length=100)),
                ('c_sector', models.CharField(max_length=200)),
                ('c_provisions', models.TextField()),
            ],
        ),
    ]
