# Generated by Django 2.2.1 on 2020-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_centralgov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
    ]
