# Generated by Django 2.2.1 on 2020-07-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemesgov',
            name='central_status',
            field=models.CharField(default='issued', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='state_status',
            field=models.CharField(default='requested', max_length=50),
            preserve_default=False,
        ),
    ]
