# Generated by Django 2.2.1 on 2020-07-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0005_auto_20200726_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemesgov',
            name='status',
        ),
    ]
