# Generated by Django 2.2.1 on 2020-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0006_remove_schemesgov_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemesgov',
            name='funds',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
