# Generated by Django 2.2.1 on 2020-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_schemesgov_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemesgov',
            name='rejreason',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
