# Generated by Django 2.2.1 on 2020-07-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0010_auto_20200729_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='modify',
            name='rejreason',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modify',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
