# Generated by Django 2.2.1 on 2020-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0011_auto_20200730_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='modify',
            name='centralauthfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modify',
            name='centralminfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modify',
            name='docs',
            field=models.FileField(default='pending', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modify',
            name='stateauthfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modify',
            name='stateminfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
