# Generated by Django 2.2.1 on 2020-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0012_auto_20200730_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modify',
            name='centralauthfundstatus',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='centralminfundstatus',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='stateauthfundstatus',
        ),
        migrations.RemoveField(
            model_name='modify',
            name='stateminfundstatus',
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='centralauthfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='centralminfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='docs',
            field=models.FileField(default='pending', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='stateauthfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemesgov',
            name='stateminfundstatus',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
