# Generated by Django 2.2.1 on 2020-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0014_schemesgov_reminstall'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=500)),
                ('ministry', models.CharField(max_length=100)),
                ('efficiency', models.CharField(max_length=100)),
                ('repcan', models.TextField()),
                ('suggestion', models.TextField()),
                ('remark', models.TextField()),
                ('docs', models.FileField(upload_to='')),
            ],
        ),
    ]
