# Generated by Django 2.2.1 on 2020-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0015_stateauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modify',
            old_name='status',
            new_name='central_status',
        ),
        migrations.AddField(
            model_name='modify',
            name='state_status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemesgov',
            name='docs',
            field=models.FileField(upload_to='scheme'),
        ),
        migrations.AlterField(
            model_name='stateauth',
            name='docs',
            field=models.FileField(upload_to='auth'),
        ),
    ]
