# Generated by Django 2.2.1 on 2020-08-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0017_auto_20200802_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemesgov',
            name='install',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
